edition = "2021"
unstable_features = true
brace_style = "SameLineWhere"
attr_fn_like_width = 70
control_brace_style = "AlwaysSameLine"
indent_style = "Block"
max_width = 100
chain_width = 30
error_on_line_overflow = true
tab_spaces = 4
newline_style = "Unix"
wrap_comments = true
imports_indent = "Block"
reorder_imports = true
group_imports = "StdExternalCrate"
reorder_modules = true
